# Generated by Django 5.2.16 on 2026-07-28 13:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0038_merge_20250527_1404"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="access_protocol",
            field=models.CharField(
                choices=[
                    ("ARCHIPEL", "Archipelago"),
                    ("ARKIVUM", "Arkivum"),
                    ("DV", "Dataverse"),
                    ("DC", "DuraCloud"),
                    ("DSPACE", "DSpace via SWORD2 API"),
                    ("DSPC_RST", "DSpace via REST API"),
                    ("FEDORA", "FEDORA via SWORD2"),
                    ("GPG", "GPG encryption on Local Filesystem"),
                    ("FS", "Local Filesystem"),
                    ("LOM", "LOCKSS-o-matic"),
                    ("NFS", "NFS"),
                    ("REPLICA", "Write-Only Replica Staging on Local Filesystem"),
                    ("PIPE_FS", "Pipeline Local Filesystem"),
                    ("RCLONE", "RClone"),
                    ("SWIFT", "Swift"),
                    ("S3", "S3"),
                    ("WELLCOME", "Wellcome Storage Service"),
                ],
                help_text="How the space can be accessed.",
                max_length=8,
                verbose_name="Access protocol",
            ),
        ),
    ]
