# Generated by Django 5.2.16 on 2026-07-30 06:28

from django.contrib.auth.management import create_permissions
from django.db import migrations


def add_wellcome_manager_permissions(apps, schema_editor):
    app_config = apps.get_app_config("locations")
    app_config.models_module = True
    try:
        create_permissions(
            app_config,
            apps=apps,
            verbosity=0,
            using=schema_editor.connection.alias,
        )
    finally:
        app_config.models_module = None

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type = ContentType.objects.get_for_model(
        apps.get_model("locations", "WellcomeStorageService")
    )

    manager = Group.objects.get(name="Managers")
    manager.permissions.add(*Permission.objects.filter(content_type=content_type))


def remove_wellcome_manager_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    content_type = ContentType.objects.get_for_model(
        apps.get_model("locations", "WellcomeStorageService")
    )

    manager = Group.objects.get(name="Managers")
    manager.permissions.remove(*Permission.objects.filter(content_type=content_type))


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0039_alter_space_access_protocol"),
    ]

    operations = [
        migrations.RunPython(
            add_wellcome_manager_permissions,
            remove_wellcome_manager_permissions,
        ),
    ]
