# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-17 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0029_auto_20200122_0726'),
        ('locations', '0030_user_groups'),
    ]

    operations = [
    ]
