steps:
  - command: .buildkite/scripts/run_autoformat.py
    label: "run autoformatting"

  - wait

  - label: ":python: s3_start_transfer tests"
    command: .buildkite/scripts/run_lambda_tests.sh s3_start_transfer

  - label: ":python: transfer_monitor tests"
    command: .buildkite/scripts/run_lambda_tests.sh transfer_monitor

  - wait

  - label: ":docker: dashboard"
    command: archivematica-apps/archivematica/build_and_publish_image.sh dashboard
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::299497370133:role/workflow-ci"

  - label: ":docker: MCP client"
    command: archivematica-apps/archivematica/build_and_publish_image.sh mcp-client
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::299497370133:role/workflow-ci"

  - label: ":docker: MCP server"
    command: archivematica-apps/archivematica/build_and_publish_image.sh mcp-server
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::299497370133:role/workflow-ci"

  - label: ":docker: Archivematica storage service"
    command: archivematica-apps/archivematica-storage-service/build_and_publish_image.sh
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::299497370133:role/workflow-ci"

  - label: ":docker: nginx"
    commands:
      - 
      - "./.buildkite/scripts/build_docker_image.sh archivematica-nginx"
      - "./.buildkite/scripts/publish_docker_image.sh archivematica-nginx"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::299497370133:role/workflow-ci"

  - label: ":docker: clamavd"
    commands:
      - "./.buildkite/scripts/build_docker_image.sh clamavd"
      - "./.buildkite/scripts/publish_docker_image.sh clamavd"
    plugins:
      - wellcomecollection/aws-assume-role#v0.2.2:
          role: "arn:aws:iam::299497370133:role/workflow-ci"
