# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-20 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0031_merge_20221017_0727'),
        ('locations', '0033_package_checksum'),
    ]

    operations = [
    ]
