# Generated by Django 4.2.16 on 2025-05-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0034_merge_20230720_0400'),
        ('locations', '0037_django42'),
    ]

    operations = [
    ]
